/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hl7.wim.zamowienia;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import au.com.bytecode.opencsv.CSVReader;
import hl7.wim.zamowienia.service.DokServiceZam;
import java.io.FileReader;
import javax.swing.SwingConstants;

/**
 *
 * @author k.skowronski
 */
public class HL7WIMZamWindowStart extends javax.swing.JFrame {

    /**
     * Creates new form HL7WIMZamWindowStart
     */
    public HL7WIMZamWindowStart() { 
        initComponents();
        jTextArea1.setText("1. Wskarz plik HL7 z zamówieniem, kliknij 'Otwórz plik HL7 z zam.'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Otwórz plik HL7 Zam.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("HL7 integracja CliniNet > Mapi Zamówienia v01");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pobierzPlikHL7(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HL7WIMZamWindowStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HL7WIMZamWindowStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HL7WIMZamWindowStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HL7WIMZamWindowStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HL7WIMZamWindowStart().setVisible(true);
            }
        });
    }
    
    
    // add Klaudiusz Skowroński 2015-04-14
    
    private JFileChooser fc=new JFileChooser(".");
    private String msg;
   
    public void pobierzPlikHL7()
    {
        // 01 - Wskazuje ścieżeka do pliku
        
        BufferedReader file_in = null;
            msg = "";
            
            if(fc.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)
            {
                return;
            }
            File file=fc.getSelectedFile();
            
            try {
              // file_in  = new BufferedReader(new FileReader(fc.getSelectedFile().getPath()));  
 
                file_in  = new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF8"));
                
            } catch (Exception e) {
                 throw new RuntimeException("Nie mogę pobrać pliku");
            }
            
            parsuj_dane(file);
       
    }
    
    public void parsuj_dane( File file)
    {
        
          try {
            //CSVReader reader = new CSVReader(new FileReader( file ), ';'); 
            //CSVReader reader = new CSVReader(new InputStreamReader(new FileInputStream( file ),"UTF-8"),';');
            
            //Txt reader 
            BufferedReader in = new BufferedReader( new FileReader(file));
            
            String fileLines = null;
               msg = new String();
               
               
                while ( (fileLines = in.readLine()) != null)
                {
                   String tekst = fileLines; 
                   msg = msg + tekst + (char)13;
                }
                in.close();
               
                System.out.println(msg);
                
                DokServiceZam.getInstance().parsuj(msg);
                        
                 
          
            
            // tabelaDokumentow = myEntries.toArray();
        } catch (IOException ex) {
           System.out.println("Wystapil blad:" + ex.getLocalizedMessage() );
        }
          
        System.out.println("Koniec");
        
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
